name: ci
on:
  push:
    branches: ['main', 'releases/**']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

        # min. npm v7 is required for the tests
      - name: update npm
        if: startsWith(matrix.node-version, '14')
        run: npm install -g npm@7

        # install dependencies for root and all sub packages
      - name: install dependencies main
        run: npm ci
      - name: install dependencies semver
        working-directory: packages/semver
        run: npm ci

      - name: test affected
        run: npx nx affected:test --base=origin/main~1 --head=HEAD
      - name: lint affected
        run: npx nx affected:lint --base=origin/main~1 --head=HEAD
      - name: build affected
        run: npx nx affected:build --base=origin/main~1 --head=HEAD

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # install dependencies for root and all sub packages
      - name: install dependencies main
        run: npm ci
      - name: install dependencies semver
        working-directory: packages/semver
        run: npm ci

      - name: build affected
        run: npx nx affected:build --base=origin/main~1 --head=HEAD

      - name: bump version
        run: npm run bump

      - name: check semver dist exists
        id: check_semver_dist
        uses: andstor/file-existence-action@v1
        with:
          files: 'dist/packages/semver/package.json'

      - name: publish semver
        if: steps.check_semver_dist.outputs.files_exists == 'true'
        working-directory: dist/packages/semver
        run: npm publish --ignore-scripts --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
