name: ci
on:
  push:
    branches: [ 'main', 'releases/**' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies main
        run: npm ci
      - name: install dependencies semver
        working-directory: packages/semver
        run: npm ci
      - name: test affected in PR
        if: ${{ github.event_name == 'pull_request' }}
        run: npx nx affected:test --base=origin/main --head=HEAD
      - name: test affected in main
        if: ${{ github.event_name != 'pull_request' }}
        run: npx nx affected:test --base=origin/main~1 --head=HEAD

